name: Docs
on:
  push:
    paths-ignore:
      - '*.md'
      - '.mailmap'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    env:
      JOB_NAME: Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          find .jenkins.d/ -type f -name '[1-9]*.sh' -exec chmod -x '{}' +
          ./.jenkins
      - name: Build documentation
        run: |
          pybindir=$(python3 -c 'import sysconfig; print(sysconfig.get_path("scripts", "posix_user"))')
          export PATH="${pybindir}${PATH:+:}${PATH}"
          ./waf --color=yes configure
          ./waf --color=yes build --targets=version.hpp
          ./waf --color=yes build --targets=manpages
          ./waf --color=yes docs
