name: Docs
on:
  push:
  workflow_dispatch:

permissions: {}

jobs:
  html:
    uses: named-data/actions/.github/workflows/docs-html.yml@v1
  man:
    uses: named-data/actions/.github/workflows/docs-man.yml@v1
